# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

$FirebaseSDKVersion = '10.29.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.29.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      existing_flags = config.build_settings['WARNING_CFLAGS']
      if existing_flags.is_a?(Array)
        config.build_settings['WARNING_CFLAGS'] << '-Wno-missing-template-arg-list-after-template-kw'
      elsif existing_flags.is_a?(String)
        config.build_settings['WARNING_CFLAGS'] += ' -Wno-missing-template-arg-list-after-template-kw'
      else
        config.build_settings['WARNING_CFLAGS'] = ['-Wno-missing-template-arg-list-after-template-kw']
      end
    end
    
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end

  # Patch para o erro de template do gRPC-Core no Xcode 16 / Clang
  basic_seq_path = File.join(installer.sandbox.root, 'gRPC-Core/src/core/lib/promise/detail/basic_seq.h')
  if File.exist?(basic_seq_path)
    puts "Patching gRPC-Core's basic_seq.h for Xcode 16 compatibility..."
    File.chmod(0644, basic_seq_path) rescue nil
    content = File.read(basic_seq_path)
    if content.include?('Traits::template CallSeqFactory(f_, *cur_, std::move(arg))')
      new_content = content.gsub('Traits::template CallSeqFactory(f_, *cur_, std::move(arg))', 'Traits::template CallSeqFactory<>(f_, *cur_, std::move(arg))')
      File.write(basic_seq_path, new_content)
      puts "gRPC-Core's basic_seq.h successfully patched."
    else
      puts "gRPC-Core's basic_seq.h already patched or pattern not found."
    end
  else
    puts "Warning: gRPC-Core's basic_seq.h not found at #{basic_seq_path}"
  end
end

