default_platform(:ios)

platform :ios do
  before_all do
    if ENV["ASC_KEY_ID"] && !ENV["ASC_KEY_ID"].empty?
      app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT_B64"],
        is_key_content_base64: true,
        in_house: false
      )
    end
  end

  desc "Release new version to TestFlight"
  lane :release do
    setup_ci
    begin
      match(
        type: "appstore",
        readonly: true
      )
    rescue => e
      UI.important("Match stored certificate invalid or revoked. Running match_nuke to recreate...")
      match_nuke(
        type: "appstore",
        skip_confirmation: true
      )
      match(
        type: "appstore",
        readonly: false
      )
    end

    gym(
      scheme: "Runner",
      clean: true,
      export_method: "app-store"
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
  end
end
