default_platform(:ios)

platform :ios do
  before_all do
    # Fetch from custom environment variables to avoid Fastlane's automatic env matching
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: false,
      in_house: false
    )
  end

  desc "Fetch certificates and provisioning profiles using match"
  lane :match_appstore do
    setup_ci
    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Generate new certificates and profiles"
  lane :generate_certs do
    match(
      type: "appstore",
      readonly: false,
      force: true
    )
  end

  desc "Nuke and generate new certificates and profiles"
  lane :nuke_and_generate do
    match_nuke(
      type: "distribution",
      skip_confirmation: true
    )
    match(
      type: "appstore",
      readonly: false,
      force: true
    )
  end
end
