default_platform(:ios)

platform :ios do
  before_all do
    if ENV["ASC_KEY_ID"] && !ENV["ASC_KEY_ID"].empty?
      app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT_B64"],
        is_key_content_base64: true,
        in_house: false
      )
    end
  end

  desc "Release new version to TestFlight"
  lane :release do
    setup_ci
    match(
      type: "appstore",
      readonly: true
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj"
    )
    gym(
      scheme: "Runner",
      clean: true,
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=PJ32UPL29J",
      export_options: {
        provisioningProfiles: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
      }
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
  end
end
