import '../models/enums.dart';
import '../models/exercise.dart';

final List<LibraryExercise> defaultLibraryExercises = [
  // PEITO
  LibraryExercise(
    id: "def_peito_1",
    name: "Supino Reto com Barra",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco na cadência e controle na descida até o peito.",
  ),
  LibraryExercise(
    id: "def_peito_2",
    name: "Supino Inclinado com Halteres",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Desenvolvimento da porção superior do peitoral.",
  ),
  LibraryExercise(
    id: "def_peito_3",
    name: "Crucifixo Reto com Halteres",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Alongamento máximo das fibras peitorais na descida.",
  ),
  LibraryExercise(
    id: "def_peito_4",
    name: "Crossover Polia Média",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Foco na contração de pico no centro do peito.",
  ),
  LibraryExercise(
    id: "def_peito_5",
    name: "Flexão de Braço (Push-ups)",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Exercício básico com peso corporal.",
  ),
  LibraryExercise(
    id: "def_peito_6",
    name: "Supino Declinado com Barra",
    muscle: "Peito",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco na porção inferior do peitoral.",
  ),

  // COSTAS
  LibraryExercise(
    id: "def_costas_1",
    name: "Puxada Aberta na Polia",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Foco na expansão dorsal e adução das escápulas.",
  ),
  LibraryExercise(
    id: "def_costas_2",
    name: "Remada Curvada com Barra",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Mantenha a lombar firme e puxe a barra na linha do umbigo.",
  ),
  LibraryExercise(
    id: "def_costas_3",
    name: "Remada Baixa Sentada (Triângulo)",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Excelente exercício para espessura das costas.",
  ),
  LibraryExercise(
    id: "def_costas_4",
    name: "Barra Fixa (Pull-ups)",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Puxe o corpo até passar o queixo da barra.",
  ),
  LibraryExercise(
    id: "def_costas_5",
    name: "Remada Unilateral com Halter (Serrote)",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco no isolamento unilateral da dorsal.",
  ),
  LibraryExercise(
    id: "def_costas_6",
    name: "Levantamento Terra",
    muscle: "Costas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Exercício multiarticular de força e estabilidade geral.",
  ),

  // PERNAS (QUADRÍCEPS / POSTERIOR / PANTURRILHA)
  LibraryExercise(
    id: "def_pernas_1",
    name: "Agachamento Livre com Barra",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Base do treino de pernas. Foco na profundidade com boa postura.",
  ),
  LibraryExercise(
    id: "def_pernas_2",
    name: "Leg Press 45 Graus",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Mantenha a amplitude sem tirar a lombar do apoio.",
  ),
  LibraryExercise(
    id: "def_pernas_3",
    name: "Cadeira Extensora",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Foco na contração isométrica de pico no quadríceps.",
  ),
  LibraryExercise(
    id: "def_pernas_4",
    name: "Mesa Flexora",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Foco no isolamento dos posteriores de coxa.",
  ),
  LibraryExercise(
    id: "def_pernas_5",
    name: "Stiff com Halteres",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Alongamento máximo do posterior de coxa e glúteos.",
  ),
  LibraryExercise(
    id: "def_pernas_6",
    name: "Gêmeos Sentado (Solear)",
    muscle: "Pernas",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Foco na amplitude completa da flexão plantar.",
  ),

  // OMBROS
  LibraryExercise(
    id: "def_ombros_1",
    name: "Desenvolvimento com Halteres",
    muscle: "Ombros",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco na porção anterior e lateral do deltoide.",
  ),
  LibraryExercise(
    id: "def_ombros_2",
    name: "Elevação Lateral com Halteres",
    muscle: "Ombros",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Excelente para a largura e aspecto tridimensional dos ombros.",
  ),
  LibraryExercise(
    id: "def_ombros_3",
    name: "Elevação Frontal com Halteres",
    muscle: "Ombros",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco na porção anterior dos deltoides.",
  ),
  LibraryExercise(
    id: "def_ombros_4",
    name: "Crucifixo Invertido com Halteres",
    muscle: "Ombros",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Trabalho da porção posterior do deltoide e trapézio médio.",
  ),
  LibraryExercise(
    id: "def_ombros_5",
    name: "Encolhimento com Halteres",
    muscle: "Ombros",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Desenvolvimento da porção superior do trapézio.",
  ),

  // BÍCEPS
  LibraryExercise(
    id: "def_biceps_1",
    name: "Rosca Direta com Barra W",
    muscle: "Bíceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Clássico para força e volume geral do bíceps.",
  ),
  LibraryExercise(
    id: "def_biceps_2",
    name: "Rosca Alternada com Halteres",
    muscle: "Bíceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Gire o punho na subida para contrair o bíceps ao máximo.",
  ),
  LibraryExercise(
    id: "def_biceps_3",
    name: "Rosca Martelo com Halteres",
    muscle: "Bíceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco no braquiorradial (antebraço) e braquial.",
  ),
  LibraryExercise(
    id: "def_biceps_4",
    name: "Rosca Concentrada",
    muscle: "Bíceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Isolamento extremo do pico do bíceps.",
  ),
  LibraryExercise(
    id: "def_biceps_5",
    name: "Rosca Scott com Barra",
    muscle: "Bíceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Evita o roubo de carga usando o apoio do banco Scott.",
  ),

  // TRÍCEPS
  LibraryExercise(
    id: "def_triceps_1",
    name: "Tríceps Pulley (Corda)",
    muscle: "Tríceps",
    measurementType: MeasurementType.reps,
    executionType: "Máquina",
    notes: "Afaste as mãos no final do movimento para contração máxima.",
  ),
  LibraryExercise(
    id: "def_triceps_2",
    name: "Tríceps Testa com Barra W",
    muscle: "Tríceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Trabalho forte da porção longa do tríceps.",
  ),
  LibraryExercise(
    id: "def_triceps_3",
    name: "Tríceps Coice com Halter",
    muscle: "Tríceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco na extensão máxima do cotovelo na contração.",
  ),
  LibraryExercise(
    id: "def_triceps_4",
    name: "Mergulho em Bancos",
    muscle: "Tríceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Exercício composto focado em peso corporal.",
  ),
  LibraryExercise(
    id: "def_triceps_5",
    name: "Tríceps Francês Unilateral",
    muscle: "Tríceps",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Foco no alongamento e isolamento unilateral.",
  ),

  // ABDÔMEN
  LibraryExercise(
    id: "def_abdo_1",
    name: "Abdominal Supra Solo",
    muscle: "Abdômen",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Retração máxima da caixa torácica em direção à pelve.",
  ),
  LibraryExercise(
    id: "def_abdo_2",
    name: "Prancha Frontal Isométrica",
    muscle: "Abdômen",
    measurementType: MeasurementType.time,
    executionType: "Livre",
    notes: "Foco na estabilidade e contração isométrica do core.",
  ),
  LibraryExercise(
    id: "def_abdo_3",
    name: "Abdominal Infra no Solo",
    muscle: "Abdômen",
    measurementType: MeasurementType.reps,
    executionType: "Livre",
    notes: "Elevação controlada das pernas com foco na pelve.",
  ),
  LibraryExercise(
    id: "def_abdo_4",
    name: "Prancha Lateral",
    muscle: "Abdômen",
    measurementType: MeasurementType.time,
    executionType: "Livre",
    notes: "Estabilidade do core com foco nos oblíquos.",
  ),

  // CARDIO
  LibraryExercise(
    id: "def_cardio_1",
    name: "Corrida na Esteira",
    muscle: "Cardio",
    measurementType: MeasurementType.time,
    executionType: "Aeróbico",
    notes: "Treino de condicionamento físico geral.",
  ),
  LibraryExercise(
    id: "def_cardio_2",
    name: "Bicicleta Ergométrica",
    muscle: "Cardio",
    measurementType: MeasurementType.time,
    executionType: "Aeróbico",
    notes: "Excelente opção de baixo impacto para articulações.",
  ),
  LibraryExercise(
    id: "def_cardio_3",
    name: "Elíptico",
    muscle: "Cardio",
    measurementType: MeasurementType.time,
    executionType: "Aeróbico",
    notes: "Treinamento cardiovascular com baixo impacto.",
  ),
  LibraryExercise(
    id: "def_cardio_4",
    name: "Corda Naval",
    muscle: "Cardio",
    measurementType: MeasurementType.time,
    executionType: "Livre",
    notes: "Alta intensidade e condicionamento metabólico.",
  ),
];
