import '../models/food_item.dart';

final List<FoodItem> presetFoods100 = [
  // --- PROTEÍNAS (1 - 10) ---
  FoodItem(
      id: 'seed_1',
      name: 'Peito de Frango Grelhado',
      searchName: 'peito de frango grelhado',
      calories: 165,
      protein: 31.0,
      carbs: 0.0,
      fat: 3.6,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_2',
      name: 'Patinho de Boi Grelhado',
      searchName: 'patinho de boi grelhado',
      calories: 219,
      protein: 35.9,
      carbs: 0.0,
      fat: 7.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_3',
      name: 'Alcatra Grelhada',
      searchName: 'alcatra grelhada',
      calories: 241,
      protein: 31.9,
      carbs: 0.0,
      fat: 11.6,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_4',
      name: 'Contra Filé Grelhado',
      searchName: 'contra file grelhado',
      calories: 278,
      protein: 29.5,
      carbs: 0.0,
      fat: 17.0,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_5',
      name: 'Filé de Tilápia Grelhado',
      searchName: 'file de tilapia grelhado',
      calories: 128,
      protein: 26.0,
      carbs: 0.0,
      fat: 2.7,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_6',
      name: 'Filé de Salmão Grelhado',
      searchName: 'file de salmao grelhado',
      calories: 206,
      protein: 22.0,
      carbs: 0.0,
      fat: 12.0,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_7',
      name: 'Atum em Lata (Escorrido)',
      searchName: 'atum em lata (escorrido)',
      calories: 116,
      protein: 26.0,
      carbs: 0.0,
      fat: 0.8,
      servingSize: 120,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_8',
      name: 'Ovo Cozido',
      searchName: 'ovo cozido',
      calories: 78,
      protein: 6.3,
      carbs: 0.6,
      fat: 5.3,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_9',
      name: 'Clara de Ovo',
      searchName: 'clara de ovo',
      calories: 17,
      protein: 3.6,
      carbs: 0.2,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_10',
      name: 'Ovo Frito',
      searchName: 'ovo frito',
      calories: 110,
      protein: 6.3,
      carbs: 0.6,
      fat: 9.0,
      servingSize: 1,
      servingUnit: 'unidade'),

  // --- LATICÍNIOS & DERIVADOS (11 - 20) ---
  FoodItem(
      id: 'seed_11',
      name: 'Leite Integral',
      searchName: 'leite integral',
      calories: 120,
      protein: 6.0,
      carbs: 10.0,
      fat: 6.0,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_12',
      name: 'Leite Desnatado',
      searchName: 'leite desnatado',
      calories: 70,
      protein: 6.0,
      carbs: 10.0,
      fat: 0.0,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_13',
      name: 'Iogurte Natural Integral',
      searchName: 'iogurte natural integral',
      calories: 126,
      protein: 6.8,
      carbs: 9.0,
      fat: 7.0,
      servingSize: 170,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_14',
      name: 'Queijo Muçarela',
      searchName: 'queijo mucarela',
      calories: 96,
      protein: 7.0,
      carbs: 0.9,
      fat: 7.5,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_15',
      name: 'Queijo Prato',
      searchName: 'queijo prato',
      calories: 105,
      protein: 6.8,
      carbs: 0.6,
      fat: 8.7,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_16',
      name: 'Queijo Cottage',
      searchName: 'queijo cottage',
      calories: 98,
      protein: 11.0,
      carbs: 3.4,
      fat: 4.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_17',
      name: 'Queijo Ricota',
      searchName: 'queijo ricota',
      calories: 140,
      protein: 11.0,
      carbs: 3.0,
      fat: 9.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_18',
      name: 'Requeijão Cremoso',
      searchName: 'requeijao cremoso',
      calories: 82,
      protein: 2.8,
      carbs: 1.0,
      fat: 7.6,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_19',
      name: 'Manteiga',
      searchName: 'manteiga',
      calories: 74,
      protein: 0.1,
      carbs: 0.1,
      fat: 8.3,
      servingSize: 10,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_20',
      name: 'Whey Protein Concentrado',
      searchName: 'whey protein concentrado',
      calories: 120,
      protein: 24.0,
      carbs: 3.0,
      fat: 1.5,
      servingSize: 30,
      servingUnit: 'g'),

  // --- GRÃOS & CEREAIS (21 - 30) ---
  FoodItem(
      id: 'seed_21',
      name: 'Arroz Branco Cozido',
      searchName: 'arroz branco cozido',
      calories: 130,
      protein: 2.5,
      carbs: 28.0,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_22',
      name: 'Arroz Integral Cozido',
      searchName: 'arroz integral cozido',
      calories: 111,
      protein: 2.6,
      carbs: 23.0,
      fat: 0.9,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_23',
      name: 'Feijão Carioca Cozido',
      searchName: 'feijao carioca cozido',
      calories: 76,
      protein: 4.8,
      carbs: 14.0,
      fat: 0.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_24',
      name: 'Feijão Preto Cozido',
      searchName: 'feijao preto cozido',
      calories: 77,
      protein: 4.5,
      carbs: 14.0,
      fat: 0.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_25',
      name: 'Grão de Bico Cozido',
      searchName: 'grao de bico cozido',
      calories: 164,
      protein: 8.9,
      carbs: 27.0,
      fat: 2.6,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_26',
      name: 'Lentilha Cozida',
      searchName: 'lentilha cozida',
      calories: 116,
      protein: 9.0,
      carbs: 20.0,
      fat: 0.4,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_27',
      name: 'Macarrão Sêmola Cozido',
      searchName: 'macarrao semola cozido',
      calories: 131,
      protein: 5.0,
      carbs: 25.0,
      fat: 1.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_28',
      name: 'Macarrão Integral Cozido',
      searchName: 'macarrao integral cozido',
      calories: 124,
      protein: 5.3,
      carbs: 26.0,
      fat: 0.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_29',
      name: 'Aveia em Flocos',
      searchName: 'aveia em flocos',
      calories: 117,
      protein: 4.3,
      carbs: 17.0,
      fat: 2.2,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_30',
      name: 'Farinha de Aveia',
      searchName: 'farinha de aveia',
      calories: 115,
      protein: 4.8,
      carbs: 18.0,
      fat: 2.0,
      servingSize: 30,
      servingUnit: 'g'),

  // --- TUBÉRCULOS, MASSAS & PÃES (31 - 40) ---
  FoodItem(
      id: 'seed_31',
      name: 'Batata Doce Cozida',
      searchName: 'batata doce cozida',
      calories: 86,
      protein: 1.6,
      carbs: 20.0,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_32',
      name: 'Batata Inglesa Cozida',
      searchName: 'batata inglesa cozida',
      calories: 87,
      protein: 1.9,
      carbs: 20.1,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_33',
      name: 'Mandioca Cozida',
      searchName: 'mandioca cozida',
      calories: 125,
      protein: 0.6,
      carbs: 30.0,
      fat: 0.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_34',
      name: 'Mandioquinha Salsa Cozida',
      searchName: 'mandioquinha salsa cozida',
      calories: 80,
      protein: 0.9,
      carbs: 18.9,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_35',
      name: 'Goma de Tapioca',
      searchName: 'goma de tapioca',
      calories: 240,
      protein: 0.0,
      carbs: 60.0,
      fat: 0.0,
      servingSize: 70,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_36',
      name: 'Cuscuz Paulista',
      searchName: 'cuscuz paulista',
      calories: 112,
      protein: 2.2,
      carbs: 25.0,
      fat: 0.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_37',
      name: 'Pão Francês',
      searchName: 'pao frances',
      calories: 137,
      protein: 4.0,
      carbs: 29.0,
      fat: 1.0,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_38',
      name: 'Pão de Forma',
      searchName: 'pao de forma',
      calories: 120,
      protein: 3.8,
      carbs: 23.0,
      fat: 1.5,
      servingSize: 2,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_39',
      name: 'Pão Integral',
      searchName: 'pao integral',
      calories: 110,
      protein: 4.5,
      carbs: 20.0,
      fat: 1.2,
      servingSize: 2,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_40',
      name: 'Pipoca Salgada (Estourada)',
      searchName: 'pipoca salgada (estourada)',
      calories: 120,
      protein: 3.0,
      carbs: 18.0,
      fat: 4.0,
      servingSize: 30,
      servingUnit: 'g'),

  // --- FRUTAS (41 - 60) ---
  FoodItem(
      id: 'seed_41',
      name: 'Banana Prata',
      searchName: 'banana prata',
      calories: 98,
      protein: 1.3,
      carbs: 26.0,
      fat: 0.3,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_42',
      name: 'Banana Nanica',
      searchName: 'banana nanica',
      calories: 92,
      protein: 1.4,
      carbs: 23.8,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_43',
      name: 'Maçã Fuji',
      searchName: 'maca fuji',
      calories: 75,
      protein: 0.3,
      carbs: 19.0,
      fat: 0.2,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_44',
      name: 'Maçã Gala',
      searchName: 'maca gala',
      calories: 72,
      protein: 0.3,
      carbs: 18.0,
      fat: 0.2,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_45',
      name: 'Laranja Pêra',
      searchName: 'laranja pera',
      calories: 62,
      protein: 1.2,
      carbs: 15.0,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_46',
      name: 'Tangerina Ponkan',
      searchName: 'tangerina ponkan',
      calories: 50,
      protein: 0.8,
      carbs: 12.0,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_47',
      name: 'Limão Taiti',
      searchName: 'limao taiti',
      calories: 12,
      protein: 0.3,
      carbs: 4.0,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_48',
      name: 'Morangos',
      searchName: 'morangos',
      calories: 32,
      protein: 0.7,
      carbs: 7.7,
      fat: 0.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_49',
      name: 'Uva Itália',
      searchName: 'uva italia',
      calories: 68,
      protein: 0.6,
      carbs: 17.0,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_50',
      name: 'Abacaxi (Pérola)',
      searchName: 'abacaxi (perola)',
      calories: 48,
      protein: 0.5,
      carbs: 12.3,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_51',
      name: 'Mamão Papaia',
      searchName: 'mamao papaia',
      calories: 43,
      protein: 0.5,
      carbs: 10.8,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_52',
      name: 'Melão Amarelo',
      searchName: 'melao amarelo',
      calories: 34,
      protein: 0.8,
      carbs: 8.2,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_53',
      name: 'Melancia',
      searchName: 'melancia',
      calories: 30,
      protein: 0.6,
      carbs: 7.5,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_54',
      name: 'Abacate',
      searchName: 'abacate',
      calories: 160,
      protein: 2.0,
      carbs: 9.0,
      fat: 15.0,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_55',
      name: 'Manga Palmer',
      searchName: 'manga palmer',
      calories: 60,
      protein: 0.8,
      carbs: 15.0,
      fat: 0.4,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_56',
      name: 'Polpa de Coco',
      searchName: 'polpa de coco',
      calories: 354,
      protein: 3.3,
      carbs: 15.2,
      fat: 33.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_57',
      name: 'Pera Williams',
      searchName: 'pera williams',
      calories: 57,
      protein: 0.4,
      carbs: 15.0,
      fat: 0.1,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_58',
      name: 'Pêssego Nacional',
      searchName: 'pessego nacional',
      calories: 39,
      protein: 0.9,
      carbs: 9.5,
      fat: 0.3,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_59',
      name: 'Kiwi',
      searchName: 'kiwi',
      calories: 61,
      protein: 1.1,
      carbs: 14.7,
      fat: 0.5,
      servingSize: 1,
      servingUnit: 'unidade'),
  FoodItem(
      id: 'seed_60',
      name: 'Ameixa Vermelha',
      searchName: 'ameixa vermelha',
      calories: 46,
      protein: 0.7,
      carbs: 11.4,
      fat: 0.3,
      servingSize: 1,
      servingUnit: 'unidade'),

  // --- LEGUMES & VERDURAS (61 - 80) ---
  FoodItem(
      id: 'seed_61',
      name: 'Brócolis Cozido',
      searchName: 'brocolis cozido',
      calories: 35,
      protein: 2.4,
      carbs: 7.0,
      fat: 0.4,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_62',
      name: 'Couve Flor Cozida',
      searchName: 'couve flor cozida',
      calories: 25,
      protein: 1.9,
      carbs: 5.0,
      fat: 0.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_63',
      name: 'Alface Americana',
      searchName: 'alface americana',
      calories: 14,
      protein: 0.9,
      carbs: 3.0,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_64',
      name: 'Alface Crespa',
      searchName: 'alface crespa',
      calories: 15,
      protein: 1.3,
      carbs: 2.9,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_65',
      name: 'Tomate Saladete',
      searchName: 'tomate saladete',
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_66',
      name: 'Cenoura Cozida',
      searchName: 'cenoura cozida',
      calories: 35,
      protein: 0.8,
      carbs: 8.2,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_67',
      name: 'Beterraba Cozida',
      searchName: 'beterraba cozida',
      calories: 43,
      protein: 1.6,
      carbs: 9.6,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_68',
      name: 'Abobrinha Cozida',
      searchName: 'abobrinha cozida',
      calories: 17,
      protein: 1.2,
      carbs: 3.1,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_69',
      name: 'Chuchu Cozido',
      searchName: 'chuchu cozido',
      calories: 19,
      protein: 0.8,
      carbs: 4.5,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_70',
      name: 'Vagem Cozida',
      searchName: 'vagem cozida',
      calories: 31,
      protein: 1.8,
      carbs: 7.0,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_71',
      name: 'Espinafre Cozido',
      searchName: 'espinafre cozido',
      calories: 23,
      protein: 3.0,
      carbs: 3.6,
      fat: 0.3,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_72',
      name: 'Couve Manteiga Refogada',
      searchName: 'couve manteiga refogada',
      calories: 49,
      protein: 2.2,
      carbs: 6.1,
      fat: 2.0,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_73',
      name: 'Pepino Japonês',
      searchName: 'pepino japones',
      calories: 15,
      protein: 0.7,
      carbs: 3.6,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_74',
      name: 'Rabanete',
      searchName: 'rabanete',
      calories: 16,
      protein: 0.7,
      carbs: 3.4,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_75',
      name: 'Cebola',
      searchName: 'cebola',
      calories: 40,
      protein: 1.1,
      carbs: 9.3,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_76',
      name: 'Alho',
      searchName: 'alho',
      calories: 149,
      protein: 6.4,
      carbs: 33.0,
      fat: 0.5,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_77',
      name: 'Pimentão Verde',
      searchName: 'pimentao verde',
      calories: 20,
      protein: 0.9,
      carbs: 4.6,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_78',
      name: 'Repolho Branco',
      searchName: 'repolho branco',
      calories: 25,
      protein: 1.3,
      carbs: 5.8,
      fat: 0.1,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_79',
      name: 'Berinjela Cozida',
      searchName: 'berinjela cozida',
      calories: 25,
      protein: 1.0,
      carbs: 6.0,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_80',
      name: 'Quiabo Refogado',
      searchName: 'quiabo refogado',
      calories: 33,
      protein: 1.9,
      carbs: 7.5,
      fat: 0.2,
      servingSize: 100,
      servingUnit: 'g'),

  // --- OLEAGINOSAS & GORDURAS BOAS (81 - 90) ---
  FoodItem(
      id: 'seed_81',
      name: 'Azeite de Oliva Extra Virgem',
      searchName: 'azeite de oliva extra virgem',
      calories: 119,
      protein: 0.0,
      carbs: 0.0,
      fat: 13.0,
      servingSize: 13,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_82',
      name: 'Pasta de Amendoim Integral',
      searchName: 'pasta de amendoim integral',
      calories: 180,
      protein: 7.0,
      carbs: 6.0,
      fat: 15.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_83',
      name: 'Castanha do Pará',
      searchName: 'castanha do para',
      calories: 186,
      protein: 4.0,
      carbs: 3.0,
      fat: 19.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_84',
      name: 'Castanha de Caju Tostada',
      searchName: 'castanha de caju tostada',
      calories: 160,
      protein: 5.0,
      carbs: 9.0,
      fat: 12.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_85',
      name: 'Amêndoas Sem Sal',
      searchName: 'amendoas sem sal',
      calories: 170,
      protein: 6.0,
      carbs: 6.0,
      fat: 15.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_86',
      name: 'Nozes',
      searchName: 'nozes',
      calories: 196,
      protein: 4.5,
      carbs: 4.0,
      fat: 19.5,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_87',
      name: 'Linhaça Marrom',
      searchName: 'linhaca marrom',
      calories: 53,
      protein: 1.8,
      carbs: 2.9,
      fat: 4.2,
      servingSize: 10,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_88',
      name: 'Sementes de Chia',
      searchName: 'sementes de chia',
      calories: 49,
      protein: 1.7,
      carbs: 4.2,
      fat: 3.1,
      servingSize: 10,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_89',
      name: 'Semente de Girassol Tostada',
      searchName: 'semente de girassol tostada',
      calories: 175,
      protein: 6.0,
      carbs: 6.0,
      fat: 15.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_90',
      name: 'Óleo de Coco Extra Virgem',
      searchName: 'oleo de coco extra virgem',
      calories: 120,
      protein: 0.0,
      carbs: 0.0,
      fat: 14.0,
      servingSize: 13,
      servingUnit: 'ml'),

  // --- BEBIDAS & OUTROS (91 - 100) ---
  FoodItem(
      id: 'seed_91',
      name: 'Suco de Laranja Integral',
      searchName: 'suco de laranja integral',
      calories: 90,
      protein: 1.4,
      carbs: 22.0,
      fat: 0.2,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_92',
      name: 'Suco de Uva Integral',
      searchName: 'suco de uva integral',
      calories: 120,
      protein: 0.6,
      carbs: 28.0,
      fat: 0.0,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_93',
      name: 'Café sem Açúcar',
      searchName: 'cafe sem acucar',
      calories: 2,
      protein: 0.1,
      carbs: 0.0,
      fat: 0.0,
      servingSize: 100,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_94',
      name: 'Chá Verde Infusão',
      searchName: 'cha verde infusao',
      calories: 1,
      protein: 0.0,
      carbs: 0.0,
      fat: 0.0,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_95',
      name: 'Água de Coco',
      searchName: 'agua de coco',
      calories: 38,
      protein: 0.4,
      carbs: 9.0,
      fat: 0.4,
      servingSize: 200,
      servingUnit: 'ml'),
  FoodItem(
      id: 'seed_96',
      name: 'Chocolate Amargo 70%',
      searchName: 'chocolate amargo 70%',
      calories: 170,
      protein: 2.0,
      carbs: 13.0,
      fat: 12.0,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_97',
      name: 'Chocolate ao Leite',
      searchName: 'chocolate ao leite',
      calories: 161,
      protein: 2.1,
      carbs: 17.6,
      fat: 9.1,
      servingSize: 30,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_98',
      name: 'Açúcar Refinado',
      searchName: 'acucar refinado',
      calories: 39,
      protein: 0.0,
      carbs: 10.0,
      fat: 0.0,
      servingSize: 10,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_99',
      name: 'Mel de Abelha',
      searchName: 'mel de abelha',
      calories: 30,
      protein: 0.0,
      carbs: 8.2,
      fat: 0.0,
      servingSize: 10,
      servingUnit: 'g'),
  FoodItem(
      id: 'seed_100',
      name: 'Sal Refinado',
      searchName: 'sal refinado',
      calories: 0,
      protein: 0.0,
      carbs: 0.0,
      fat: 0.0,
      servingSize: 5,
      servingUnit: 'g'),
];
