name: Fastlane Match Init

on:
  workflow_dispatch:

jobs:
  generate_certs:
    name: Generate Certificates
    runs-on: macos-26
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ios

      - name: Fastlane Match (Generate)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_PAT: ${{ secrets.MATCH_PAT }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          cd ios
          bundle exec fastlane generate_certs --verbose
